### PR TITLE
Added: Intro to Info-Sec Quiz-2

### PR DESCRIPTION
**Pull request by krishnaNallasingu**

### CODE REVIEW

**Comment by krishnaNallasingu** [comment]
Hey Hi
Here I can add some of the Previous papers of IIIT-H Examinations for your better learning and understanding purpose

**Comment by PraneethJain** [comment]
Hey
- Since this is an elective, please move it to the Electives folder 
- The folder name should start with the 3 letter abbreviation, view the naming convention
- Remove the .DS_Store files added

Thanks!

**Comment by krishnaNallasingu** [comment]
Thank you for your info
Sure :)

**Comment by PraneethJain** [comment]
Closing this as #39 already added the papers.

**Pull request closed without merging**
