### PR TITLE
Added year3/CND and 2 other courses

### PR DESCRIPTION
**Pull request by PranavAga**
created course folders for: 
- Year3/CND (4)
- Elective/CsFree/DSI (1)

Updated Year2/CS/AT

Only added pdfs for M23

### CODE REVIEW

**Comment by PraneethJain** [comment]
Hey,
You've modified 3 files from DBS 2016 and deleted ITWS (ISS) 2018 mid1?

**Comment by PranavAga** [comment]
Didn't do it intentionally, there was some issue when I pulled the repo. Should I add them back?

**Comment by PranavAga** [comment]
> Hey, You've modified 3 files from DBS 2016 and deleted ITWS (ISS) 2018 mid1?

The content of the DBS files are same for both branches, don't know why they were considered different.
For ITWS, I tried adding the deleted folder, but it shows 'invalid folder name'.

**Comment by PraneethJain** [comment]
Seems like colon (:) is invalid in paths on Windows, which is the case for ITWS. I've removed the colon and re-uploaded the file.

**Pull request merged**
