### PR TITLE
added new papers

### PR DESCRIPTION
**Pull request by Prithvi-k**
- 2023 PRS Quiz 1
- 2023 PRS Midsem QP
- 2023 Science 1 Quiz 1

### CODE REVIEW

**Review by PraneethJain — CHANGES_REQUESTED** [review]
Hey, could you rename `PRS_mid_2023_M.pdf` to `PRS_mid1_2023_M.pdf`

**Comment by Prithvi-k** [comment]
Yep, done

**Comment by PraneethJain** [comment]
> Yep, done

Thanks!

**Review by PraneethJain — COMMENTED** [review]
:+1:

**Review by PraneethJain — COMMENTED** [review]
:+1:

**Pull request merged**
